import "./globals.css";
import "../style.css";
import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import Header from "./components/sections/header/Header";
import FooterSection from "./components/sections/footer/Footer";

const inter = Inter({ subsets: ["latin"] });
const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Header />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
